sudo: false
language: go

services:
- redis-server

go:
  - 1.9
  - tip

matrix:
  allow_failures:
    - go: tip

install:
  - go get -u github.com/golang/dep/cmd/dep

before_script:
  - redis-server --port 6380 &

script:
  - go test -race $(go list ./... | grep -v /vendor/)